import {allEntries,aliens,roster,characters,bens,devices,regions,eras,playlist,evolvedForm,combine,wiki} from './data.js';
import {thumbnail} from './sprites.js';
import {World} from './world.js';
const $=id=>document.getElementById(id);
function readSaved(){try{return JSON.parse(localStorage.getItem('omniverse-v1')||'{}');}catch{return {};}}
const saved=readSaved(),params=new URLSearchParams(location.search);
let deviceId=devices.some(d=>d.id===params.get('device'))?params.get('device'):devices.some(d=>d.id===saved.device)?saved.device:'classic';
let dnaId=params.get('dna')||saved.dna||'heatblast',fusionId='alien-x',inspected=null,soundEnabled=false,busy=false;
const seen=new Set(Array.isArray(saved.seen)?saved.seen.filter(x=>allEntries.some(e=>e.id===x)):[]);
let toastTimeout;function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').classList.remove('visible'),3200);}
function save(){try{localStorage.setItem('omniverse-v1',JSON.stringify({device:deviceId,dna:dnaId,seen:[...seen]}));}catch{}}
function updateUrl(){const query=new URLSearchParams({device:deviceId,dna:dnaId,sector:world.region});try{history.replaceState(null,'',`?${query}`);}catch{}save();}
function dismissTitle() {document.querySelector('.scene-title').classList.add('dismissed');}
function regionChanged(id){const r=regions.find(r=>r.id===id);$('region-name').textContent=r.name;$('region-subtitle').textContent=r.subtitle;document.querySelectorAll('.minimap button').forEach(el=>el.classList.toggle('selected',el.dataset.region===id));updateUrl();}
const world=new World($('world'),{onSelect:inspect,onRegion:regionChanged,onTransformDone:entry=>{busy=false;$('transform').disabled=false;$('transform-label').textContent='TRANSFORM';$('active-form').textContent=`${entry.name} active · ${device().short}`;toast(`${entry.name}. It’s hero time.`);}});
function device(){return devices.find(d=>d.id===deviceId);}
function currentPlaylist(){return playlist(deviceId,{expanded:$('expanded').checked});}
function currentDNA(){return currentPlaylist().find(a=>a.id===dnaId);}
function option(value,text){const o=document.createElement('option');o.value=value;o.textContent=text;return o;}
for(const d of devices)$('device-select').append(option(d.id,d.name));
for(const a of aliens)$('fusion-select').append(option(a.id,a.name));
for(const d of devices.slice(0,4)){
 const b=document.createElement('button');b.className='device-tab';b.dataset.device=d.id;b.innerHTML='<span class="mini-watch" aria-hidden="true"></span>';b.append(document.createTextNode(d.short));b.onclick=()=>setDevice(d.id);$('device-tabs').append(b);
}
regions.forEach((r,i)=>{const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0');b.dataset.region=r.id;b.title=r.name;b.setAttribute('aria-label',`Explore ${r.name}`);b.onclick=()=>{dismissTitle();world.focusRegion(r.id);};$('minimap').append(b);});
function setDevice(id){if(busy){toast('Wait for the transformation to finish.');return;}if(!devices.some(d=>d.id===id))return;deviceId=id;$('ultimate').checked=false;renderDevice();updateUrl();}
function renderDevice(){
 const d=device();document.documentElement.style.setProperty('--accent',d.color);$('device-select').value=d.id;document.querySelectorAll('.device-tab').forEach(b=>{const selected=b.dataset.device===d.id;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});
 const list=currentPlaylist();if(!list.some(a=>a.id===dnaId))dnaId=list[0].id;
 $('dna-select').replaceChildren(...list.map(a=>option(a.id,a.name)));$('dna-select').value=dnaId;
 $('fusion-control').hidden=d.mode!=='fusion';$('ultimate-control').hidden=d.mode!=='ultimate';$('expanded-control').hidden=d.mode==='predator';
 if(fusionId===dnaId)fusionId=aliens.find(a=>a.id!==dnaId).id;$('fusion-select').value=fusionId;
 renderDNA();
}
function renderDNA(){
 const a=currentDNA(),d=device();$('dna-image').src=thumbnail(a,d.color);$('dna-image').alt=`${a.name} miniature`;$('dna-species').textContent=a.species;
 const ultimate=evolvedForm(a.id,d.id);$('ultimate').disabled=!ultimate;if(!ultimate)$('ultimate').checked=false;
 $('ultimate-control').title=ultimate?ultimate.name:'This DNA sample has no verified Ultimate form on this device.';
 if(fusionId===dnaId){fusionId=aliens.find(a=>a.id!==dnaId).id;$('fusion-select').value=fusionId;}
 for(const o of $('fusion-select').options)o.disabled=o.value===dnaId;
 $('transform-label').textContent=d.mode==='predator'?'SIMULATE PREDATOR':d.mode==='fusion'?'FUSE DNA':'TRANSFORM';
}
function cycleDNA(step){if(busy)return;const list=currentPlaylist(),i=list.findIndex(a=>a.id===dnaId);dnaId=list[(i+step+list.length)%list.length].id;$('dna-select').value=dnaId;renderDNA();updateUrl();}
let audioContext;
function playSound(){if(!soundEnabled)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});const start=audioContext.currentTime;for(let i=0;i<3;i++){const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.setValueAtTime(180+i*180,start+i*.075);osc.frequency.exponentialRampToValueAtTime(950+i*80,start+i*.075+.18);gain.gain.setValueAtTime(.0001,start+i*.075);gain.gain.exponentialRampToValueAtTime(.07,start+i*.075+.025);gain.gain.exponentialRampToValueAtTime(.0001,start+i*.075+.25);osc.connect(gain);gain.connect(audioContext.destination);osc.start(start+i*.075);osc.stop(start+i*.075+.26);}}catch{soundEnabled=false;$('sound').textContent='Sound unavailable';}}
function transform(){
 if(busy)return;const d=device();let a=currentDNA();if(!a)return;
 if(d.mode==='fusion'){a=combine(a.id,fusionId);if(!a){toast('Select two different base DNA samples to fuse.');return;}}
 if($('ultimate').checked){const evolved=evolvedForm(a.id,d.id);if(evolved)a=evolved;}
 busy=true;$('transform').disabled=true;$('transform-label').textContent='TRANSFORMING…';$('active-form').textContent=`Synchronising ${a.name}…`;dismissTitle();$('inspector').hidden=true;seen.add(a.id);save();playSound();
 const wielder=bens.find(b=>b.device===d.id);world.transform(a,d.color,wielder);
}
function inspect(entry){
 inspected=entry;world.active=entry.id;seen.add(entry.id);save();$('inspector').hidden=false;$('inspect-kind').textContent=(entry.kind==='ben'?'MULTIVERSE WIELDER':entry.kind.toUpperCase())+` / ${eras[entry.era]??'FIELD GUIDE'}`;
 $('inspect-name').textContent=entry.name;$('inspect-species').textContent=entry.species;$('inspect-task').textContent=entry.task;$('inspect-note').textContent=entry.note||entry.continuity||'';$('inspect-image').src=thumbnail(entry,entry.kind==='ben'?entry.color:device().color);$('inspect-image').alt=`${entry.name} miniature`;$('inspect-source').href=entry.source;
 $('inspect-dna').hidden=entry.kind==='character';$('inspect-dna').textContent=entry.kind==='ben'?'Use this device':entry.kind==='fusion'?'Load fusion':entry.kind==='ultimate'?'Load Ultimate DNA':'Select DNA';dismissTitle();
}
function loadEntry(entry){
 if(busy){toast('Wait for the transformation to finish.');return;}
 if(entry.kind==='ben'){if(entry.device==='none'){toast('No Watch Ben has no Omnitrix. Explore his timeline instead.');world.focusEntry(entry.id);return;}setDevice(entry.device);toast(`${entry.name}’s device selected.`);return;}
 if(entry.kind==='ultimate'){setDevice(entry.era==='ov'?'albedo':'ultima');dnaId=entry.base;renderDevice();$('ultimate').checked=true;}
 else if(entry.kind==='predator'){setDevice('neme');dnaId=entry.id;renderDevice();}
 else if(entry.kind==='fusion'){setDevice('bio');[dnaId,fusionId]=entry.components;renderDevice();}
 else if(entry.kind==='supplemental'){$('expanded').checked=true;setDevice('omni');dnaId=entry.id;renderDevice();}
 else{if(!currentPlaylist().some(a=>a.id===entry.id))setDevice(entry.era==='classic'?'classic':entry.era==='af'?'af':entry.era==='ua'?'ultima':'omni');dnaId=entry.id;renderDevice();}
 updateUrl();toast(`${entry.name} DNA selected. Press Transform.`);
}
function showArchive(filter='all'){if(busy){toast('Wait for the transformation to finish.');return;}$('archive-filter').value=filter;$('archive-search').value='';renderArchive();$('archive-dialog').showModal();$('archive-search').focus();}
function renderArchive(){
 const filter=$('archive-filter').value,query=$('archive-search').value.trim().toLowerCase(),playlistIds=new Set(currentPlaylist().map(a=>a.id));
 const list=allEntries.filter(e=>{const type=filter==='all'||(filter==='playlist'?playlistIds.has(e.id):e.kind===filter||e.era===filter);const text=[e.name,e.species,e.task,e.note,eras[e.era],e.continuity,e.prey].filter(Boolean).join(' ').toLowerCase();return type&&text.includes(query);});
 $('archive-title').textContent=filter==='ben'?'Across the timelines.':filter==='playlist'?`${device().short} playlist.`:'DNA archive.';$('result-count').textContent=`${list.length} entries`;$('discovered-count').textContent=`${seen.size} discovered / ${allEntries.length} residents`;
 const fragment=document.createDocumentFragment();
 for(const e of list){const b=document.createElement('button');b.className='archive-card';b.setAttribute('aria-label',`Inspect ${e.name}`);const tag=document.createElement('span');tag.className='card-kind';tag.textContent=`${e.kind} / ${eras[e.era]??'UNIVERSE'}`;const img=document.createElement('img');img.src=thumbnail(e);img.alt='';img.loading='lazy';const strong=document.createElement('strong');strong.textContent=e.name;const small=document.createElement('small');small.textContent=e.species;b.append(tag,img,strong,small);if(seen.has(e.id)){const s=document.createElement('span');s.className='seen';s.textContent='✓';s.title='Discovered';b.append(s);}b.onclick=()=>{$('archive-dialog').close();inspect(e);world.focusEntry(e.id);};fragment.append(b);}
 if(!list.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='No matches in this catalogue. Try another name, species or filter.';fragment.append(empty);}$('archive-grid').replaceChildren(fragment);
}
function showInfo(eyebrow,title,html){$('info-eyebrow').textContent=eyebrow;$('info-title').textContent=title;$('info-body').innerHTML=html;$('info-dialog').showModal();}
function help(){showInfo('YOUR FIELD GUIDE','Welcome to the Omniverse.',`<p>A living isometric fan world inspired by Floor796. Every resident has a repeating motion. Explore twelve districts, inspect characters, and try the Omnitrix transformation simulator.</p><div class="keyboard-row"><span>Pan the scene</span><kbd>Drag / arrows</kbd></div><div class="keyboard-row"><span>Zoom</span><kbd>Scroll / pinch / + −</kbd></div><div class="keyboard-row"><span>Transform</span><kbd>Space</kbd></div><div class="keyboard-row"><span>Browse the archive</span><kbd>A</kbd></div><div class="keyboard-row"><span>Pause animations</span><kbd>P</kbd></div><div class="keyboard-row"><span>Fit the whole world</span><kbd>F</kbd></div><p>Click a miniature to see its action and source. Choose a device, select DNA, then transform. The Ultimatrix offers verified Ultimate forms; the Biomnitrix mixes two samples; the Nemetrix demonstrates predator transformations on a suitable host.</p><p>Discovery progress is saved on this browser. Reduced-motion preferences pause the scene on arrival. Sound starts off.</p>`);}
function sources(){showInfo('CURATED CATALOGUE / RESEARCH NOTES','A universe, carefully labelled.',`<div class="info-grid"><div><strong>${aliens.length}</strong>Base transformation entries</div><div><strong>${roster.length}</strong>DNA entries including variants</div><div><strong>${characters.length}</strong>Friends, foes & supporting cast</div><div><strong>${bens.length}</strong>Era avatars & alternate wielders</div></div><p>This first edition covers the four original-continuity series, their major transformations and a broad supporting cast. It is a curated catalogue, not an exhaustive index of every comic, incidental character or unseen DNA sample.</p><p>Classic includes the future-Ben introductions Arctiguana, Buzzshock and Spitter. Nanomech is grouped with the Alien Force era and Shocksquatch with Ultimate Alien / Heroes United. Upchuck’s two subspecies are separate entries. Later watch playlists use cumulative, curated availability rather than reproducing each episode’s lock state.</p><p>Ultimate Grey Matter is presented under that familiar archive name and linked to Ultimate Albedo. Supplementary concepts, stage-show aliens and non-canon game forms are labelled. Unseen designs are schematic interpretations. Spitter’s comic archive entry references the existing alien, not a new species. Newly published comic continuities are not merged into the original TV timeline.</p><p>Alternate devices share simulator playlists; they do not imply every alternate Ben used every form on screen. Non-screen Biomnitrix pairs are explicitly fan simulations. All miniatures and loops are original simplified fan art, with shared animation rigs.</p><ul class="info-list"><li><a href="${wiki('Omnitrix (Original)')}" target="_blank" rel="noopener noreferrer">Prototype Omnitrix / Classic and Alien Force playlists ↗</a></li><li><a href="${wiki('Ultimatrix (Original)')}" target="_blank" rel="noopener noreferrer">Ultimatrix / Ultimate Alien playlist ↗</a></li><li><a href="${wiki('Omnitrix (Omniverse)')}" target="_blank" rel="noopener noreferrer">Completed Omnitrix / Omniverse roster ↗</a></li><li><a href="${wiki('Ultimate Forms')}" target="_blank" rel="noopener noreferrer">Ultimate forms ↗</a></li><li><a href="${wiki('Biomnitrix')}" target="_blank" rel="noopener noreferrer">Biomnitrix and screen fusions ↗</a></li><li><a href="${wiki('Nemetrix')}" target="_blank" rel="noopener noreferrer">Nemetrix predator roster ↗</a></li><li><a href="https://en.wikipedia.org/wiki/List_of_Ben_10_characters" target="_blank" rel="noopener noreferrer">Characters and timelines ↗</a></li><li><a href="https://floor796.com/" target="_blank" rel="noopener noreferrer">Floor796 / inspiration ↗</a></li></ul><p>Ben 10 characters and names belong to their respective rights holders. This project is an unofficial fan experiment and has no affiliation with Cartoon Network, Warner Bros. or Floor796. Catalogue researched October 2026.</p>`);}
function deviceInfo(){const d=device();showInfo('DEVICE DOSSIER',d.name,`<div class="device-illustration ${d.shape}" aria-hidden="true">⌛</div><p>${d.note}</p><p>${currentPlaylist().length} selectable DNA entries in the current playlist.</p><p>Switch devices using the four era buttons or the alternate-device selector. ${d.mode==='ultimate'?'Enable Ultimate evolution only when the selected sample has a verified form.':d.mode==='fusion'?'Pick a second base sample. Known screen pairs use a named fusion; other pairs are labelled fan simulations.':d.mode==='predator'?'The simulation uses a predator host; this device is not a normal human-Ben Omnitrix.':'The transformation flash uses the selected device colour.'}</p>`);}
$('archive-count').textContent=String(roster.length);$('world-count').textContent=String(allEntries.length);
$('archive-open').onclick=()=>showArchive();$('dna-open').onclick=()=>showArchive('playlist');$('timelines-open').onclick=()=>showArchive('ben');$('world-tab').onclick=()=>{$('inspector').hidden=true;dismissTitle();world.fit();};$('help-open').onclick=help;$('sources-open').onclick=sources;$('device-info').onclick=deviceInfo;
$('device-select').onchange=e=>setDevice(e.target.value);$('dna-select').onchange=e=>{if(busy){e.target.value=dnaId;return;}dnaId=e.target.value;renderDNA();updateUrl();};$('fusion-select').onchange=e=>{fusionId=e.target.value;};$('expanded').onchange=()=>{renderDevice();updateUrl();};$('dna-prev').onclick=()=>cycleDNA(-1);$('dna-next').onclick=()=>cycleDNA(1);$('transform').onclick=transform;
$('ultimate').onchange=()=>{const evolved=evolvedForm(dnaId,deviceId);if($('ultimate').checked&&evolved){$('dna-image').src=thumbnail(evolved,device().color);$('dna-species').textContent=evolved.species;}else renderDNA();};
$('sound').onclick=()=>{soundEnabled=!soundEnabled;$('sound').setAttribute('aria-pressed',String(soundEnabled));$('sound').textContent=soundEnabled?'Sound on':'Sound off';if(soundEnabled)playSound();};
function togglePause(){world.paused=!world.paused;$('pause').textContent=world.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',world.paused?'Resume animation':'Pause animation');$('pause').setAttribute('aria-pressed',String(world.paused));document.querySelector('.live-status').innerHTML=world.paused?'<i></i> WORLD IS PAUSED':'<i></i> WORLD IS ALIVE';}
$('pause').onclick=togglePause;if(world.paused){world.paused=false;togglePause();}
$('zoom-in').onclick=()=>{dismissTitle();world.zoomBy(1.2);};$('zoom-out').onclick=()=>{dismissTitle();world.zoomBy(1/1.2);};$('fit').onclick=()=>{dismissTitle();world.fit();};$('explore').onclick=()=>{dismissTitle();world.fit();};$('labels').onclick=()=>{world.showLabels=!world.showLabels;$('labels').setAttribute('aria-pressed',String(world.showLabels));};$('region-next').onclick=()=>{dismissTitle();const i=regions.findIndex(r=>r.id===world.region);world.focusRegion(regions[(i+1)%regions.length].id);};
$('random').onclick=()=>{const entry=allEntries[Math.floor(Math.random()*allEntries.length)];inspect(entry);world.focusEntry(entry.id);};$('inspector-close').onclick=()=>{$('inspector').hidden=true;};$('inspect-focus').onclick=()=>world.focusEntry(inspected.id);$('inspect-dna').onclick=()=>loadEntry(inspected);
$('archive-search').oninput=renderArchive;$('archive-filter').onchange=renderArchive;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}));
$('world').addEventListener('pointerdown',dismissTitle);$('world').addEventListener('wheel',dismissTitle,{passive:true});
document.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,dialog')||document.querySelector('dialog[open]'))return;if(e.code==='Space'&&e.target.tagName==='BUTTON')return;const key=e.key.toLowerCase();if(e.code==='Space'){e.preventDefault();transform();}else if(key==='a')showArchive();else if(key==='p')togglePause();else if(key==='f'){dismissTitle();world.fit();}else if(key==='+'||key==='=')world.zoomBy(1.2);else if(key==='-')world.zoomBy(1/1.2);else if(key==='escape')$('inspector').hidden=true;else if(['arrowleft','arrowright','arrowup','arrowdown'].includes(key)){e.preventDefault();dismissTitle();const step=50/world.camera.zoom;if(key==='arrowleft')world.camera.x-=step;if(key==='arrowright')world.camera.x+=step;if(key==='arrowup')world.camera.y-=step;if(key==='arrowdown')world.camera.y+=step;world.constrain();}});
renderDevice();if(regions.some(r=>r.id===params.get('sector')))world.focusRegion(params.get('sector'),false);regionChanged(world.region);
