import { allEntries } from './data.js';

// Fan vignettes inspired by character abilities and familiar settings. These are
// invented activity loops, not claims that these scenes appear in an episode.
const byName = new Map(allEntries.map(entry => [entry.name, entry]));
const idFor = name => {
  const entry = byName.get(name);
  if (!entry) throw new Error(`Unknown scene character: ${name}`);
  return entry.id;
};
const palettes = {
  camp: ['#577347','#29443b','#cce78a','#819b73'],
  city: ['#455463','#243341','#7eb8dd','#607b94'],
  forest: ['#385d43','#193b31','#a8ca5b','#618472'],
  desert: ['#99764e','#4f483c','#edbf68','#b7a085'],
  lab: ['#425853','#223b3b','#a7e666','#557775'],
  hangar: ['#46515a','#263641','#86c7cd','#5a7484'],
  space: ['#373347','#17172e','#ae9ee7','#252844'],
  anur: ['#484257','#242338','#b3a0d2','#52516d'],
  nullvoid: ['#654853','#302639','#d998b2','#694f73'],
  arena: ['#796952','#3d3c3b','#e0c087','#928570'],
  underwater: ['#276c7a','#183d50','#7edee2','#2f8ea2'],
  volcano: ['#774b41','#3f3032','#ff9e55','#974c43'],
  ice: ['#668b9a','#354b62','#b4e9f1','#91b3be'],
  ruins: ['#7c765d','#3e493e','#cec88e','#9b9a7b'],
  swamp: ['#4c6145','#293d35','#b8ca77','#72836b'],
  undertown: ['#635473','#302d46','#d8a4df','#79648a'],
  multiverse: ['#465272','#272842','#99c6f8','#56628d']
};
const sceneRows = [
['camp','Rust Bucket campsite','The summer that started everything','classic','camp',['Classic Ben','Gwen Tennyson','Grandpa Max','Kevin Levin','Heatblast','Four Arms','XLR8','Wildmutt','Diamondhead']],
['family-picnic','Tennyson family picnic','Disguises, maps and a quiet afternoon','classic','camp',['Lucy Mann','Sandra Tennyson','Carl Tennyson']],
['smoothy','Mr. Smoothy plaza','A date, a serve and a shape-shifting friend','af','city',['Alien Force Ben','Julie Yamamoto','Ship']],
['bellwood','Bellwood patrol','Ben and Rook keep the streets in motion','ov','city',['Ben Prime','Rook Blonko']],
['academy','Plumber cadet course','Speed drills, strength tests and a watch check','ua','arena',['Ultimate Alien Ben','Alan Albright','Manny Armstrong','Helen Wheels','Pierce Wheels']],
['neighbourhood','Tennyson neighbourhood','An ordinary day with an extraordinary news report','af','city',['Natalie Tennyson','Frank Tennyson','Will Harangue']],
['tidal-cavern','Tidal cavern','Water jets, currents and slippery footing','ua','underwater',['Ripjaws','Water Hazard','Walkatrout','Squidstrictor']],
['marsh-greenhouse','Marsh greenhouse','Vines grow while fire and slime take turns','af','swamp',['Wildvine','Stinkfly','Swampfire']],
['desert-quarry','Desert quarry','Drilling, recycling and a splash of goo','ua','desert',['Armodrillo','Eatle','Spitter']],
['reactor','Reactor containment bay','Heat is vented and a reactor sphere is balanced','ov','volcano',['NRG','Atomix']],
['frost-cavern','Frost cavern','Ice drifts through an electric current','af','ice',['Big Chill','Arctiguana','Ampfibian']],
['micro-lab','Micro-engineering lab','Tiny circuits meet enormous intelligence','classic','lab',['Grey Matter','Brainstorm','Nanomech','Upgrade','Chamalien','Gutrot']],
['galvan','Galvan research complex','Omnitrix calibration and a scanner that needs fixing','ov','lab',['Azmuth','Myaxx','Cooper','Blukic','Driba','Skurd']],
['workshop','Alien engineering workshop','A brick arch and a very unusual power supply','ov','hangar',['Jury Rigg','Bloxx','Feedback','Lodestar','Buzzshock','Shocksquatch']],
['resonance','Resonance testing chamber','Sonic waves and precision beams','af','lab',['Echo Echo','Blitzwolfer','Eye Guy']],
['canopy','Canopy obstacle trail','Webs, jumps, tongues and dream dust','ov','forest',['Spidermonkey','Crashhopper','Bullfrag','Pesky Dust','Mole-Stache']],
['sparring','Heavyweight sparring yard','A boulder, a dummy and a very patient target','af','arena',['Humungousaur','Rath','Kickin Hawk','The Worst','Princess Looma','Cannonbolt','Fasttrack']],
['flight-deck','High-altitude flight deck','Jet trails circle a wind-powered course','ua','hangar',['Jetray','Terraspin','Astrodactyl']],
['forge','Cosmic observation platform','A miniature galaxy and gravity in balance','ov','space',['Way Big','Alien X','Gravattack']],
['petropia','Petropian crystal terrace','Energy is refracted into a growing crystal formation','af','ruins',['Chromastone','Sugilite','Tetrax Shard']],
['recycling','Gourmand recycling depot','Scrap, doubles and a rolling plasma ball','ov','undertown',['Goop','Upchuck (Perk)','Upchuck (Murk)','Ditto','Ball Weevil']],
['anur','Anur night passage','Bandages, coils and figures in the mist','ov','anur',['Ghostfreak','Snare-Oh','Frankenstrike','Whampire']],
['spell-court','Mana spell court','A staff, a spellbook and a hungry energy orb','af','ruins',['Hex','Charmcaster','Darkstar']],
['haunted-carnival','Haunted carnival','A cage opens as the circus comes alive','classic','anur',['Zs’Skayr','Zombozo','Frightwig','Thumbskull','Acid Breath','Toepick']],
['animo','Animo mutation greenhouse','The mutation ray meets an insect swarm','classic','swamp',['Doctor Animo','Clancy']],
['malware','Corrupted research lab','Nanochips and a Nemetrix circuit under test','ov','lab',['Malware','Doctor Psychobos','Elena Validus','Rojo']],
['rooter-base','Rooter surveillance base','Equipment is monitored and stored energy is studied','ua','nullvoid',['Servantis','Aggregor']],
['conquest','Vilgax command deck','A conquest map above the Incursean fleet','ov','space',['Vilgax','Psyphon','Attea','Emperor Milleous']],
['bounty-dock','Bounty-hunter docking bay','Armour, targeting gear and sharpened tools','classic','hangar',['Sixsix','Sevenseven','EightEight','Kraab','Sunder']],
['knight-fortress','Forever Knight fortress','Sword drills inside the stone battlements','ua','ruins',['Enoch','Sir George','Forever Knight']],
['plumbers','Plumber headquarters','Patrols, scanners and hovering equipment','ov','hangar',['Magister Labrid','Magister Patelliday','Magister Hulka','Xylene']],
['galactic-training','Galactic Enforcer training','Flight, telekinesis and Tetramand strength','classic','arena',['Ultimos','Synaptek','Tini']],
['relic-expedition','Relic expedition','An ancient artefact beside a stellar chart','ov','ruins',['Kai Green','Reinrassig III']],
['anodite-garden','Anodite constellation garden','Mana ribbons curl around the stars','af','space',['Verdona','Sunny']],
['undertown','Undertown market','Street performances, coins and a shop to sweep','ov','undertown',['Pakmar','Hokestar','Argit','Ester']],
['undertown-docks','Undertown service docks','A ship, metal plates and heavy lifting','ov','hangar',['Rad Dudesman','Fistrick','Fistina']],
['vreedle-outpost','Vreedle outpost','Questionable machines beside the family camp','ov','desert',['Octagon Vreedle','Rhomboid Vreedle','Ma Vreedle']],
['billions','Billions robotics plaza','Robots are programmed and armour polished','ua','city',['Billy Billions','Captain Nemesis']],
['ultimate-strength','Ultimate strength course','Evolved strength, spines and cannon salvos','ua','arena',['Ultimate Humungousaur','Ultimate Wildmutt','Ultimate Spidermonkey','Ultimate Rath','Ultimate Cannonbolt']],
['ultimate-elements','Ultimate elemental chamber','Sonic discs and evolved fire and ice','ua','ice',['Ultimate Swampfire','Ultimate Big Chill','Ultimate Echo Echo','Ultimate Arctiguana']],
['ultimate-cosmos','Ultimate cosmic laboratory','Gravity orbits and amplified intelligence','ov','space',['Ultimate Way Big','Ultimate Gravattack','Ultimate Grey Matter']],
['fusion-giants','Biomnitrix giant platform','Two DNA signatures in one towering silhouette','ov','space',['Atomic-X','Fourmungousaur','Big Chuck']],
['fusion-workshop','Biomnitrix experiment workshop','Mechanical, elastic and electrical combinations','ov','lab',['Uprigg','Humungoopsaur','Crashocker']],
['fusion-classic','Prototype fusion field','Classic accidental combinations in a fan test course','classic','camp',['Stink Arms','Diamond Matter','Heat Jaws']],
['predator-quarry','Nemetrix rocky habitat','Shells, tunnels and sticky traps','ov','desert',['Crabdozer','Slamworm','Tyrannopede','Mucilator']],
['predator-marsh','Nemetrix mist habitat','Webs, tentacles and hypnotic patterns','ov','swamp',['Buglizard','Terroranchula','Hypnotick','Vicetopus']],
['predators','Nemetrix forest trail','A hunter watches predators on the move','ov','forest',['Omnivoracious','Panuncian','Ultimate Panuncian','Zed','Khyber']],
['multiverse','Crossroads of time','No two watches tell exactly the same story','multiverse','multiverse',['Professor Paradox','Eon','Maltruant','Clockwork','No Watch Ben','Ben 23','Gwen 10']],
['ken-training','Ken’s future training yard','A replica watch and a future hero in practice','multiverse','city',['Ken Tennyson','Ken Tennyson (watch)']],
['future-city','Future Bellwood','Different futures, different Omnitrix designs','multiverse','city',['Ben 10,000 (Classic)','Ultimate Ben','Ben 10,000 (Omniverse)','Argit (Argitrix)']],
['alternate-bens','Fractured timeline crossing','Watch colours from worlds that went another way','multiverse','multiverse',['Albedo','Bad Ben','Mad Ben','Nega Ben','Benzarro']],
['dagon-rift','Dagon dimensional rift','A vast presence behind the breach','ua','nullvoid',['Dagon']],
['archive-concepts','Concept archive vault','Unseen and disputed designs stay labelled as references','supplemental','lab',['Shellhead','Sandbox','Snakepit','Alien Z','Ventrilosquid','Decimus Prime']],
['archive-extras','Beyond-screen archive','Stage, game and comic records under inspection','supplemental','lab',['Rocks','Portaler','Antigravitesla','Bob the Blob','Plantapocalypse','Spitter (comic archive)']]
];

export const scenes = sceneRows.map(([id,name,subtitle,era,theme,names],index) => {
  const [ground,wall,accent,sky] = palettes[theme];
  return {id,name,subtitle,era,theme,palette:{ground,wall,accent,sky},color:accent,
    entries:names.map(idFor),x:index % 7,y:Math.floor(index / 7)};
});
export const sceneFor = entryOrId => {
  const id = typeof entryOrId === 'string' ? entryOrId : entryOrId?.id;
  return scenes.find(scene => scene.entries.includes(id));
};

// Explicit per-character staging; periods are seconds. The engine animates
// positions and props, while genuine source frame clips retain their own poses.
const activityRows = [
['Classic Ben','Selects and presses the prototype Omnitrix','watch','watch',3.6],
['Gwen Tennyson','Shapes a mana shield beside the camp','cast','mana',4.6],
['Grandpa Max','Turns dinner on the Rust Bucket grill','repair','grill',4.2],
['Kevin Levin','Works a wrench beside his muscle car','repair','tools',4.4],
['Heatblast','Forms and releases a fireball','aim','fire',3.2],
['Four Arms','Lifts an engine with all four arms','grow','weight',4.3],
['XLR8','Sprints around the marked speed circuit','run','speed',2.2],
['Wildmutt','Follows a scent trail through the grass','patrol','scent',5.4],
['Diamondhead','Raises and resets a crystal shield','cast','crystal',4.7],
['Grey Matter','Repairs a tiny illuminated circuit','repair','circuit',4.1],
['Stinkfly','Hovers and drops a glob of slime','fly','slime',4.8],
['Ripjaws','Swims a loop through the tidal cavern','swim','water',4.6],
['Upgrade','Flows into and out of a terminal','absorb','circuit',4.4],
['Ghostfreak','Phases through the Anur mist','vanish','mist',5.5],
['Cannonbolt','Rolls around a bumper course','roll','speed',3.3],
['Wildvine','Extends a vine toward a trellis','stretch','vine',5.2],
['Blitzwolfer','Releases a pulsing sonic howl','roar','sound',4.6],
['Snare-Oh','Uncoils and gathers his bandages','stretch','bandage',5.8],
['Frankenstrike','Charges his shoulder coils','cast','electric',4.2],
['Upchuck (Perk)','Pulls scrap toward his mouth','tongue','scrap',4.9],
['Ditto','Splits into a playful pair of doubles','split','clone',5.4],
['Eye Guy','Aims a precision eye beam','aim','beam',4.5],
['Way Big','Sweeps a cosmic ray across a practice beacon','aim','cosmic',6.8],
['Arctiguana','Freezes and thaws a small target','aim','ice',4.8],
['Buzzshock','Bounces a charge between power cells','split','electric',3.1],
['Spitter','Spits a glob toward a quarry target','aim','slime',5.0],
['Swampfire','Reignites a flower among growing vines','cast','fire',5.2],
['Echo Echo','Sends rings of sound through the chamber','split','sound',3.8],
['Humungousaur','Grows and lifts a training boulder','grow','weight',5.8],
['Jetray','Loops between aerial markers','fly','beam',4.2],
['Big Chill','Floats through a frost-covered arch','vanish','ice',6.0],
['Chromastone','Absorbs light and returns a refracted beam','absorb','crystal',5.6],
['Brainstorm','Solves a circuit with electrical arcs','cast','electric',4.9],
['Spidermonkey','Swings along a repeating web line','stretch','web',4.1],
['Goop','Reshapes under his anti-gravity projector','stretch','slime',5.0],
['Alien X','Holds a miniature galaxy in orbit','orbit','cosmic',8.4],
['Lodestar','Suspends scrap in a magnetic field','orbit','metal',5.7],
['Rath','Strikes a sparring dummy with his claws','strike','claw',3.4],
['Nanomech','Flies close to a microchip scanner','fly','circuit',3.8],
['Upchuck (Murk)','Consumes and recycles a scrap pile','tongue','scrap',5.1],
['Water Hazard','Sprays two jets into a water wheel','aim','water',4.6],
['Ampfibian','Floats while weaving electric currents','fly','electric',5.4],
['Armodrillo','Drills and clears a practice tunnel','dig','drill',4.2],
['Terraspin','Spins a controlled gust across the deck','spin','wind',4.5],
['NRG','Vents heat inside his containment suit','cast','heat',5.9],
['Fasttrack','Runs a relay between two markers','run','speed',2.8],
['Chamalien','Fades into a patterned wall','vanish','camouflage',5.7],
['Eatle','Chews scrap and releases an energy beam','absorb','beam',5.0],
['Clockwork','Rewinds a gear through a short time loop','cast','clock',6.3],
['Jury Rigg','Builds and dismantles a workshop gadget','repair','tools',3.2],
['Shocksquatch','Sparks between his fingertips','cast','electric',4.1],
['Feedback','Absorbs and returns an energy pulse','absorb','electric',4.3],
['Bloxx','Builds and collapses a colourful arch','stretch','blocks',5.1],
['Gravattack','Keeps stones orbiting his gravity field','orbit','gravity',7.1],
['Crashhopper','Hops over three canopy hurdles','hop','speed',3.1],
['Ball Weevil','Rolls an expanding plasma ball','roll','plasma',4.4],
['Walkatrout','Slides along a wet stone ledge','swim','water',4.9],
['Pesky Dust','Sprinkles dream dust over the grove','fly','dream',6.2],
['Mole-Stache','Lifts a crate with his prehensile moustache','stretch','moustache',4.6],
['The Worst','Absorbs the impact of a training bumper','absorb','impact',5.3],
['Kickin Hawk','Practices a rotating kick on a dummy','strike','impact',3.8],
['Toepick','Opens and closes his frightening face cage','roar','fear',6.6],
['Astrodactyl','Loops a jet-assisted flight course','fly','jet',4.0],
['Bullfrag','Flicks his tongue toward canopy targets','tongue','tongue',4.2],
['Atomix','Balances a glowing reactor sphere','cast','nuclear',6.4],
['Gutrot','Mixes coloured gas inside the chamber','cast','gas',5.5],
['Whampire','Flutters through the dark passage','fly','shadow',5.4],
['Ultimate Swampfire','Releases a burst of blue flame','aim','bluefire',5.2],
['Ultimate Humungousaur','Fires a practice salvo from his missile hands','aim','missile',5.1],
['Ultimate Big Chill','Sends a red freezing flame through an arch','fly','freezingfire',6.0],
['Ultimate Cannonbolt','Rolls a spiked shell around the course','roll','spikes',3.9],
['Ultimate Echo Echo','Orbits and pulses his sonic discs','orbit','sound',5.6],
['Ultimate Spidermonkey','Stomps forward and casts a web line','strike','web',5.3],
['Ultimate Wildmutt','Prowls and tests his tail against a target','patrol','tail',5.7],
['Ultimate Way Big','Flies past a cosmic beacon','fly','cosmic',7.4],
['Ultimate Arctiguana','Sends twin ice streams at a target','aim','ice',5.0],
['Ultimate Gravattack','Floats with smaller planetoids in orbit','orbit','gravity',7.8],
['Ultimate Rath','Practices an evolved claw strike','strike','claw',4.3],
['Ultimate Grey Matter','Studies a floating intelligence puzzle','cast','circuit',6.1],
['Atomic-X','Balances a fusion-powered cosmic sphere','cast','cosmic',7.5],
['Fourmungousaur','Lifts two training weights','grow','weight',5.6],
['Uprigg','Merges into a gadget and rebuilds it','repair','circuit',4.2],
['Big Chuck','Draws a scrap target toward his mouth','tongue','scrap',6.2],
['Crashocker','Hops between electrically charged markers','hop','electric',3.7],
['Humungoopsaur','Stretches a massive liquid silhouette','stretch','slime',5.9],
['Stink Arms','Flies low and throws a slime glob','fly','slime',5.1],
['Diamond Matter','Studies and grows a small crystal structure','repair','crystal',5.2],
['Heat Jaws','Sends a heated water burst at a target','aim','steam',5.0],
['Crabdozer','Charges toward a fireproof quarry barrier','strike','impact',4.9],
['Buglizard','Prowls through clouds of obscuring gas','patrol','gas',5.9],
['Mucilator','Sets a sticky sack trap beside the trail','cast','slime',5.5],
['Slamworm','Burrows between two tunnel openings','burrow','sand',6.1],
['Terroranchula','Casts an energy web over a target','cast','web',5.3],
['Hypnotick','Flutters through a hypnotic ring pattern','fly','hypnosis',6.5],
['Omnivoracious','Circles above a Galvan-sized trail','fly','wind',5.2],
['Vicetopus','Reaches out with gripping tentacles','stretch','tentacle',6.2],
['Tyrannopede','Patrols and snaps at a training target','roar','jaw',6.0],
['Panuncian','Splits into a hunting pair','split','clone',5.8],
['Ultimate Panuncian','Prowls with an evolved duplicate','split','clone',6.3],
['Rocks','Examines a stage-show strength exhibit','grow','stone',5.8],
['Squidstrictor','Coils tentacles around an aquatic training ring','stretch','tentacle',6.0],
['Shellhead','Inspects a named-only transformation record','watch','archive',7.0],
['Sandbox','Inspects a named-only transformation record','watch','archive',7.2],
['Snakepit','Inspects a named-only transformation record','watch','archive',7.4],
['Portaler','Inspects an Alien Maker game record','watch','archive',6.8],
['Antigravitesla','Inspects an Ultimate Access concept record','watch','archive',6.5],
['Bob the Blob','Inspects an Ultimate Access concept record','watch','archive',6.9],
['Plantapocalypse','Inspects an Ultimate Access concept record','watch','archive',7.3],
['Decimus Prime','Inspects a crew-concept transformation record','watch','archive',7.8],
['Alien Z','Inspects a crew-mentioned transformation record','watch','archive',7.6],
['Ventrilosquid','Inspects a crew-concept transformation record','watch','archive',7.1],
['Spitter (comic archive)','Revisits a Spitter comic record','aim','slime',5.3],
['Rook Blonko','Aims and resets his Proto-Tool','aim','prototool',4.6],
['Azmuth','Examines and calibrates an Omnitrix','repair','watch',5.5],
['Professor Paradox','Checks his pocket watch beside a time rift','watch','clock',6.7],
['Julie Yamamoto','Practices a serve beside the plaza court','strike','tennis',4.8],
['Ship','Reforms his little vehicle silhouette','stretch','circuit',5.6],
['Kai Green','Examines an ancient artefact','watch','relic',6.0],
['Ken Tennyson','Practices a holographic watch selection','watch','watch',4.6],
['Verdona','Weaves a luminous mana constellation','cast','mana',7.5],
['Sunny','Swirls an Anodite mana ribbon','cast','mana',6.4],
['Lucy Mann','Changes a disguising shimmer','vanish','slime',5.4],
['Sandra Tennyson','Turns a page in a travel journal','watch','book',6.2],
['Carl Tennyson','Checks the route on a campsite map','watch','map',6.7],
['Natalie Tennyson','Reads a book by the neighbourhood garden','watch','book',7.3],
['Frank Tennyson','Waves to passing neighbours','patrol','wave',6.3],
['Cooper','Repairs a small robot with his tools','repair','tools',4.9],
['Elena Validus','Examines an isolated nanochip sample','watch','circuit',6.1],
['Alan Albright','Practices a small Pyronite fireball','aim','fire',4.3],
['Manny Armstrong','Lifts a training weight','grow','weight',4.6],
['Helen Wheels','Runs the cadet speed course','run','speed',2.9],
['Pierce Wheels','Checks a target and raises his quills','aim','spikes',5.2],
['Magister Labrid','Calibrates Plumber scanning equipment','repair','scanner',5.7],
['Magister Patelliday','Patrols the headquarters corridor','patrol','scanner',6.2],
['Magister Hulka','Leads a cadet training drill','strike','whistle',5.6],
['Blukic','Tests a newly assembled scanner','repair','scanner',4.8],
['Driba','Troubleshoots the scanner display','repair','circuit',5.3],
['Tetrax Shard','Forms and resets a crystal shield','cast','crystal',5.5],
['Myaxx','Checks a tray of DNA samples','watch','dna',6.4],
['Xylene','Telekinetically moves Plumber equipment','orbit','telekinesis',6.0],
['Reinrassig III','Watches a slowly rotating stellar chart','watch','cosmic',8.0],
['Sugilite','Rebuilds a Petropian crystal formation','cast','crystal',7.0],
['Skurd','Samples a rotating strand of DNA','stretch','dna',5.1],
['Zed','Follows a marked Nemetrix training trail','patrol','scent',5.7],
['Pakmar','Sweeps the pavement outside his storefront','repair','broom',4.5],
['Hokestar','Rehearses an Undertown street performance','cast','sparkle',5.8],
['Argit','Counts and recounts a pile of coins','watch','coins',4.6],
['Rad Dudesman','Checks his ship controls and engines','repair','tools',5.5],
['Fistrick','Lifts and lowers a heavy weight','grow','weight',4.1],
['Vilgax','Charges and fires his gauntlet','aim','beam',5.7],
['Doctor Animo','Fires a mutation ray at a specimen tank','aim','mutation',5.0],
['Hex','Turns his staff through a spell circle','cast','magic',6.2],
['Charmcaster','Opens a spellbook and summons a rune','cast','magic',5.7],
['Zs’Skayr','Floats through a shadowed doorway','vanish','shadow',7.1],
['Zombozo','Inflates a balloon at the haunted circus','cast','balloon',5.9],
['Sixsix','Checks the weapons in his bounty armour','aim','missile',5.4],
['Sevenseven','Sweeps a targeting device across the bay','aim','scanner',5.9],
['EightEight','Patrols a landing pad and checks her blasters','patrol','beam',5.6],
['Kraab','Works his mechanical claw against a target','strike','claw',4.9],
['Psyphon','Projects and rotates a conquest map','watch','map',6.7],
['Malware','Flows through a corrupted terminal','absorb','corruption',5.1],
['Doctor Psychobos','Tests a Nemetrix circuit on the bench','repair','circuit',5.3],
['Khyber','Inspects a hunter’s trophy and scans the trail','watch','trophy',6.8],
['Aggregor','Studies an energy vessel on the platform','absorb','energy',6.4],
['Darkstar','Drains and resets a glowing practice orb','absorb','energy',5.8],
['Eon','Opens and closes a time rift','cast','clock',7.2],
['Maltruant','Reassembles gears in a time machine','repair','clock',6.3],
['Servantis','Monitors the Rooter equipment display','watch','scanner',6.7],
['Attea','Studies an Incursean command map','watch','map',6.0],
['Emperor Milleous','Surveys his fleet from the command deck','watch','fleet',7.2],
['Billy Billions','Programs and tests a small robot','repair','circuit',5.2],
['Will Harangue','Records another animated news report','watch','camera',5.8],
['Captain Nemesis','Polishes his armour and tests a pose','repair','metal',6.1],
['Rojo','Tests her mechanical arm against a target','aim','beam',4.7],
['Clancy','Directs a looping swarm of insects','cast','insects',5.6],
['Enoch','Orders a knight patrol from the battlements','watch','banner',6.5],
['Sir George','Practices a sword cut in the fortress','strike','sword',5.2],
['Forever Knight','Patrols the fortress doorway','patrol','sword',6.0],
['Dagon','Shifts behind a dimensional rift','orbit','rift',8.8],
['Frightwig','Swirls her living hair toward a target','stretch','hair',5.0],
['Thumbskull','Practices a heavy punch','strike','impact',4.1],
['Acid Breath','Blows a controlled acid cloud','aim','acid',5.3],
['Sunder','Sharpens and swings his axe','strike','axe',5.7],
['Fistina','Tests her extendable mechanical arms','stretch','metal',4.8],
['Octagon Vreedle','Tests a questionable outpost device','repair','tools',5.3],
['Rhomboid Vreedle','Carries a crate across the outpost','patrol','crate',6.7],
['Ma Vreedle','Inspects the family outpost perimeter','patrol','map',6.2],
['Princess Looma','Spars with all four arms','strike','impact',4.5],
['Ester','Stretches toward a high market shelf','stretch','crate',5.6],
['Ultimos','Flies between Galactic Enforcer markers','fly','wind',6.0],
['Synaptek','Levitates and returns a training weight','orbit','telekinesis',6.5],
['Tini','Practices a Tetramand strength routine','grow','weight',5.4],
['Ben Prime','Checks the completed Omnitrix on patrol','watch','watch',4.6],
['Alien Force Ben','Checks a recalibrated Omnitrix hologram','watch','watch',4.9],
['Ultimate Alien Ben','Selects DNA on the Ultimatrix','watch','watch',4.8],
['Ben 23','Displays a blue Hero Watch hologram','watch','watch',4.5],
['Gwen 10','Selects a violet Omnitrix hologram','watch','watch',4.8],
['Bad Ben','Selects a teal alternate-timeline hologram','watch','watch',4.2],
['Mad Ben','Checks an amber Power Watch selection','watch','watch',5.0],
['Nega Ben','Checks the grey Negatrix display','watch','watch',5.8],
['Benzarro','Shuffles and raises the Zombitrix','patrol','watch',6.0],
['Albedo','Checks a red stabilizer hologram','watch','watch',4.7],
['No Watch Ben','Watches the timelines intersect','watch','rift',7.6],
['Ben 10,000 (Classic)','Checks the future Omnitrix display','watch','watch',5.1],
['Ultimate Ben','Channels an alien-power hologram','cast','watch',5.6],
['Ben 10,000 (Omniverse)','Synchronizes both Biomnitrix displays','watch','watch',5.8],
['Ken Tennyson (watch)','Practices with his replica Omnitrix','watch','watch',4.9],
['Argit (Argitrix)','Checks an Argitrix hologram','watch','watch',5.3]
];
const propColors = {
 fire:'#ff9a45',bluefire:'#65c9ff',freezingfire:'#fa8b7c',ice:'#a7e7ff',water:'#63c5f2',
 electric:'#f6e978',mana:'#e6a4f0',magic:'#c499ee',gravity:'#e6c49b',cosmic:'#b1b9ff',
 slime:'#a5d563',gas:'#b4c782',acid:'#bedc72',crystal:'#8fdfcf',sound:'#96d5ff',
 shadow:'#bfaad4',clock:'#e0c46f',mutation:'#b3ef70',plasma:'#efc965',nuclear:'#baf682',
 corruption:'#f18c53',dream:'#d5b1ed',hypnosis:'#d7acdf',steam:'#e4cbc5',watch:'#b7ed56'
};
const activities = new Map(activityRows.map(([name,label,motion,prop,period]) => {
 const entry=byName.get(name);
 if(!entry) throw new Error(`Unknown activity character: ${name}`);
 let color = propColors[prop] || entry.color;
 if(entry.kind === 'ben' && ['Ben 23','Gwen 10','Bad Ben','Mad Ben','Nega Ben','Benzarro','Albedo','Argit (Argitrix)'].includes(entry.name)) color=entry.color;
 return [entry.id,{label,motion,prop,color,period}];
}));
export function activityFor(entryOrId) {
 const id=typeof entryOrId === 'string' ? entryOrId : entryOrId?.id;
 return activities.get(id) || {label:'Observes a fan research exhibit',motion:'watch',prop:'archive',color:entryOrId?.color || '#b7ed56',period:6};
}

// Make omissions and duplicate placement fail loudly during development/build.
const assigned = scenes.flatMap(scene=>scene.entries);
if(new Set(assigned).size !== assigned.length) throw new Error('A character appears in multiple world scenes');
const missing=allEntries.filter(entry=>!assigned.includes(entry.id));
if(missing.length) throw new Error(`Missing world scenes: ${missing.map(entry=>entry.name).join(', ')}`);
const missingActivities=allEntries.filter(entry=>!activities.has(entry.id));
if(missingActivities.length) throw new Error(`Missing character activities: ${missingActivities.map(entry=>entry.name).join(', ')}`);
